import pytest

from .pages.analytics_page import AnalyticsPage
from .pages.ohboy_demo_page import OhboyDemoPage
from .pages.dialogs_page import HomeScreenUpdateDialogPage
from .pages.email_entry_page import EmailEntryPage
from .pages.firmware_update_page import FirmwareUpdatePage
from .pages.home_page import HomePage
from .pages.landing_page import LandingPage
from .pages.learn_more_page import LearnMorePage
from .pages.menu_page import MenuPage
from .pages.molding_page import MoldingPage, MoldNewTipsPage
from .pages.support_page import SupportPage
from .pages.welcome_page import WelcomePage

import time

"""That's the set of tests from all test files intended to run smoke test
Requires connected earbuds via BT classic pulled off out of the case"""


@pytest.mark.smoke_test
class TestSmokeTest:
    def test_should_be_welcome_screen(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_get_started_button()

    def test_should_be_welcome_screen_after_background(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_get_started_button()
        welcome_page.background_app_for_5_seconds()
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_get_started_button()

    def test_should_be_flow_selection_screen(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_demo_flow_button()

    def test_should_be_analytics_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.should_be_correct_analytics_subtitle()
        analytics_page.should_be_correct_share_analytics_button_text()
        analytics_page.should_be_correct_not_share_analytics_button_text()
        analytics_page.should_be_privacy_notice()

    def test_access_demo_molding_screen(self, driver):
        welcome_page = WelcomePage(driver)
        demo_page = OhboyDemoPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_demo_flow_button()
        welcome_page.tap_demo_flow_button()
        demo_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(6)
        demo_page.should_be_debug_button()

    def test_access_demo_debug_screen(self, driver):
        welcome_page = WelcomePage(driver)
        demo_page = OhboyDemoPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_demo_flow_button()
        welcome_page.tap_demo_flow_button()
        demo_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(6)
        demo_page.should_be_debug_button()
        demo_page.tap_debug_button()
        demo_page.should_be_demo_debug_screen()

    def test_check_first_two_items_codes(self, driver):
        welcome_page = WelcomePage(driver)
        demo_page = OhboyDemoPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_demo_flow_button()
        welcome_page.tap_demo_flow_button()
        demo_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(6)
        demo_page.should_be_debug_button()
        demo_page.tap_debug_button()
        demo_page.should_be_demo_debug_screen()
        demo_page.tap_first_commands_list_item()
        demo_page.tap_second_commands_list_item()

    def test_curring_mode_activation(self, driver):
        welcome_page = WelcomePage(driver)
        demo_page = OhboyDemoPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_demo_flow_button()
        welcome_page.tap_demo_flow_button()
        demo_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(6)
        demo_page.should_be_debug_button()
        demo_page.tap_debug_button()
        demo_page.activate_curring_mode()

    def test_should_be_try_them_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.should_be_correct_try_them_page_subtitle()
        molding_page.should_be_try_them_animation()
        molding_page.should_be_try_them_button()

    def test_should_be_get_ready_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.should_be_message_title1()
        molding_page.should_be_message_title2()
        molding_page.should_be_message_title3()
        molding_page.should_be_message1()
        molding_page.should_be_message2()
        molding_page.should_be_message3()
        molding_page.should_be_smile()
        molding_page.should_be_stand_by_mirror_text()
        molding_page.should_be_do_this_button()

    def test_should_be_how_is_bass_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_do_this_button()
        # How is the bass
        molding_page.should_be_how_is_bass_title()
        molding_page.should_be_correct_how_is_bass_subtitle()
        molding_page.should_be_image_volume()
        molding_page.should_be_adjust_volume_bar()
        molding_page.should_be_cancel_button()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_should_start_soon_page1(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_do_this_button()
        # How is the bass
        molding_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        molding_page.background_app_for_5_seconds()
        molding_page.should_be_get_ready_page_title()

    def test_should_start_soon_page2(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_do_this_button()
        # How is the bass
        molding_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(4)
        # Starting soon 2
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        molding_page.should_be_cancel_button()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_cancel_molding_on_count(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_do_this_button()
        # How is the bass
        molding_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(4)
        # Starting soon 2
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(4)
        # Countdown
        molding_page.should_be_cancel_button()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_molding_complete(self, driver):
        analytics_page = AnalyticsPage(driver)
        # eq_presets_page = EqPresetsPage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_do_this_button()
        # How is the bass
        molding_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(4)
        # Starting soon 2
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        # Molding starts
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        molding_page.should_be_congratulations_title()
        molding_page.should_be_congratulations_subtitle()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_skip_for_now_button()
        molding_page.should_skip_for_now_button()
        molding_page.tap_skip_for_now_button()
        time.sleep(5)
        home_page.should_be_hamburger_menu()

    def test_curring_mode_activation1(self, driver):
        welcome_page = WelcomePage(driver)
        demo_page = OhboyDemoPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_demo_flow_button()
        welcome_page.tap_demo_flow_button()
        demo_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(6)
        demo_page.should_be_debug_button()
        demo_page.tap_debug_button()
        demo_page.activate_curring_mode()

    def test_molding_complete_and_open_learn_more(self, driver):
        analytics_page = AnalyticsPage(driver)
        learn_more_page = LearnMorePage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_do_this_button()
        # How is the bass
        molding_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(4)
        # Starting soon 2
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        # Molding starts
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        molding_page.should_be_congratulations_title()
        molding_page.should_be_congratulations_subtitle()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_skip_for_now_button()
        molding_page.should_skip_for_now_button()
        molding_page.tap_take_the_tour_button()
        learn_more_page.should_be_double_tap_control_title()
        learn_more_page.should_be_double_tap_control_animation()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.tap_learn_more_menu_icon()
        # Quit learn more
        learn_more_page.tap_learn_more_menu_icon()
        home_page.should_be_hamburger_menu()

    def test_curring_mode_activation2(self, driver):
        welcome_page = WelcomePage(driver)
        demo_page = OhboyDemoPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_demo_flow_button()
        welcome_page.tap_demo_flow_button()
        demo_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(6)
        demo_page.should_be_debug_button()
        demo_page.tap_debug_button()
        demo_page.activate_curring_mode()

    def test_molding_complete_and_open_learn_more1(self, driver):
        analytics_page = AnalyticsPage(driver)
        learn_more_page = LearnMorePage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        molding_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        # Try them on
        molding_page.should_be_try_them_page_title()
        molding_page.tap_try_them_button()
        # Get ready
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_do_this_button()
        # How is the bass
        molding_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(4)
        # Starting soon 2
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        # Molding starts
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        molding_page.should_be_congratulations_title()
        molding_page.should_be_congratulations_subtitle()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_skip_for_now_button()
        molding_page.should_skip_for_now_button()
        molding_page.tap_take_the_tour_button()
        learn_more_page.should_be_double_tap_control_title()
        learn_more_page.should_be_double_tap_control_animation()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.tap_learn_more_menu_icon()
        # Quit learn more
        learn_more_page.tap_learn_more_menu_icon()
        home_page.should_be_hamburger_menu()

    @pytest.mark.xfail
    def test_learn_more_carousel(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenUpdateDialogPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        learn_more_page = LearnMorePage(driver)
        menu_page = MenuPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        landing_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        dialog_page.check_and_close_fw_update_dialog()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_learn_more_item()
        # Double tap control
        learn_more_page.should_be_double_tap_control_title()
        # learn_more_page.should_be_double_tap_control_subtitle()
        learn_more_page.should_be_double_tap_control_animation()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_left()
        # Custom Control
        learn_more_page.should_be_custom_control_title()
        learn_more_page.should_be_custom_control_subtitle()
        learn_more_page.should_be_custom_control_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_left()
        # Switching devices
        learn_more_page.should_be_switching_devices_title()
        learn_more_page.should_be_switching_devices_subtitle()
        learn_more_page.should_be_switching_devices_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_left()
        # EQ Customization
        learn_more_page.should_be_eq_customization_title()
        learn_more_page.should_be_eq_customization_subtitle()
        learn_more_page.should_be_eq_customization_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_left()
        # Test your fit
        learn_more_page.should_be_test_your_fit_title()
        learn_more_page.should_be_test_your_fit_subtitle()
        learn_more_page.should_be_test_your_fit_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_left()
        # Pair a new device
        learn_more_page.should_be_pair_new_device_title()
        learn_more_page.should_be_pair_new_device_subtitle()
        learn_more_page.should_be_pair_new_device_animation()
        learn_more_page.should_be_pair_new_device_notice()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_left()
        # Status Indicators
        learn_more_page.should_be_status_indicators_title()
        learn_more_page.should_be_status_indicators_subtitle()
        learn_more_page.should_be_status_indicators_image()
        learn_more_page.should_be_status_indicators_notice()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_right()
        # Pair a new device
        learn_more_page.should_be_pair_new_device_title()
        learn_more_page.should_be_pair_new_device_subtitle()
        learn_more_page.should_be_pair_new_device_animation()
        learn_more_page.should_be_pair_new_device_notice()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_right()
        # Test your fit
        learn_more_page.should_be_test_your_fit_title()
        learn_more_page.should_be_test_your_fit_subtitle()
        learn_more_page.should_be_test_your_fit_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_right()
        # EQ Customization
        learn_more_page.should_be_eq_customization_title()
        learn_more_page.should_be_eq_customization_subtitle()
        learn_more_page.should_be_eq_customization_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_right()
        # Switching devices
        learn_more_page.should_be_switching_devices_title()
        learn_more_page.should_be_switching_devices_subtitle()
        learn_more_page.should_be_switching_devices_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_right()
        # Custom Control
        learn_more_page.should_be_custom_control_title()
        learn_more_page.should_be_custom_control_subtitle()
        learn_more_page.should_be_custom_control_image()
        learn_more_page.should_be_learn_more_menu_icon()
        learn_more_page.swipe_right()
        # Double tap control
        learn_more_page.should_be_double_tap_control_title()
        # learn_more_page.should_be_double_tap_control_subtitle()
        learn_more_page.should_be_double_tap_control_animation()
        learn_more_page.should_be_learn_more_menu_icon()
        # Quit learn more
        learn_more_page.tap_learn_more_menu_icon()
        menu_page.should_be_learn_more_item()

    def test_mold_new_tips_carousel(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenUpdateDialogPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        menu_page = MenuPage(driver)
        mold_new_tips_page = MoldNewTipsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        landing_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        dialog_page.check_and_close_fw_update_dialog()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_mold_new_tips_item()
        # Change your tips
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_change_tips_animation()
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.should_be_change_tips_subtitle()
        # Remove inserts
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_remove_inserts_image()
        mold_new_tips_page.should_be_remove_inserts_title()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        # Match them up
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_match_them_image()
        mold_new_tips_page.should_be_match_them_up_title()
        # mold_new_tips_page.should_be_match_them_up_subtitle()
        # Attach your tips
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_attach_tips_image()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.should_be_attach_your_tips_subtitle()
        # Check the fit
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_check_the_fit_image()
        mold_new_tips_page.should_be_check_the_fit_title()
        mold_new_tips_page.should_be_check_the_fit_subtitle()
        # Attach your tips
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_attach_tips_image()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.should_be_attach_your_tips_subtitle()
        # Match them up
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_match_them_image()
        mold_new_tips_page.should_be_match_them_up_title()
        # mold_new_tips_page.should_be_match_them_up_subtitle()
        # Remove inserts
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_remove_inserts_image()
        mold_new_tips_page.should_be_remove_inserts_title()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        # Change your tips
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_mnt_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_change_tips_animation()
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.should_be_change_tips_subtitle()
        # Return to Home screen
        mold_new_tips_page.tap_mnt_menu_icon()
        menu_page.should_be_mold_new_tips_item()

    def test_mnt_how_to_pair_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenUpdateDialogPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        menu_page = MenuPage(driver)
        mold_new_tips_page = MoldNewTipsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        landing_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        dialog_page.check_and_close_fw_update_dialog()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_mold_new_tips_item()
        # Carousel
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_match_them_up_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_check_the_fit_title()
        mold_new_tips_page.tap_next_button()
        # How to pair screen
        mold_new_tips_page.should_be_how_to_pair_title()
        mold_new_tips_page.should_be_how_to_pair_subtitle()
        mold_new_tips_page.should_be_how_to_pair_animation()
        mold_new_tips_page.should_be_got_it_button()
        mold_new_tips_page.should_be_back_arrow()
        mold_new_tips_page.tap_got_it_button()
        # Try them on screen
        time.sleep(10)
        mold_new_tips_page.should_be_try_them_page_title()
        mold_new_tips_page.should_be_correct_try_them_page_subtitle()
        mold_new_tips_page.should_be_try_them_animation()
        mold_new_tips_page.should_be_try_them_button()
        mold_new_tips_page.should_be_back_arrow()
        mold_new_tips_page.tap_back_arrow()
        mold_new_tips_page.tap_back_arrow()
        mold_new_tips_page.should_be_check_the_fit_title()

    def test_mnt_get_ready_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenUpdateDialogPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        menu_page = MenuPage(driver)
        mold_new_tips_page = MoldNewTipsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        landing_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        dialog_page.check_and_close_fw_update_dialog()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_mold_new_tips_item()
        # Carousel
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_match_them_up_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_check_the_fit_title()
        mold_new_tips_page.tap_next_button()
        # How to pair screen
        mold_new_tips_page.should_be_got_it_button()
        mold_new_tips_page.tap_got_it_button()
        # Try them on screen
        time.sleep(10)
        mold_new_tips_page.should_be_try_them_button()
        mold_new_tips_page.tap_try_them_button()
        # Get Ready screen
        mold_new_tips_page.should_be_get_ready_page_title()
        mold_new_tips_page.should_be_message_title1()
        mold_new_tips_page.should_be_message_title2()
        mold_new_tips_page.should_be_message_title3()
        mold_new_tips_page.should_be_message1()
        mold_new_tips_page.should_be_message2()
        mold_new_tips_page.should_be_message3()
        mold_new_tips_page.should_be_smile()
        mold_new_tips_page.should_be_stand_by_mirror_text()
        mold_new_tips_page.should_be_do_this_button()
        mold_new_tips_page.should_be_back_arrow()
        mold_new_tips_page.tap_back_arrow()
        mold_new_tips_page.should_be_try_them_button()

    def test_mnt_warnings(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenUpdateDialogPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        menu_page = MenuPage(driver)
        mold_new_tips_page = MoldNewTipsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        landing_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        dialog_page.check_and_close_fw_update_dialog()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_mold_new_tips_item()
        # Carousel
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_match_them_up_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_check_the_fit_title()
        mold_new_tips_page.tap_next_button()
        # How to pair screen
        mold_new_tips_page.should_be_got_it_button()
        mold_new_tips_page.tap_got_it_button()
        # Try them on screen
        time.sleep(10)
        mold_new_tips_page.should_be_try_them_button()
        mold_new_tips_page.tap_try_them_button()
        # Get ready
        mold_new_tips_page.should_be_get_ready_page_title()
        mold_new_tips_page.tap_do_this_button()
        # How is the bass
        mold_new_tips_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        mold_new_tips_page.should_be_starting_soon_title()
        mold_new_tips_page.should_be_starting_soon_subtitle1()
        time.sleep(4)
        # Starting soon 2
        mold_new_tips_page.should_be_starting_soon_title()
        mold_new_tips_page.should_be_starting_soon_subtitle2()
        time.sleep(4)
        # Countdown
        mold_new_tips_page.should_be_cancel_button()
        mold_new_tips_page.background_app_for_5_seconds()
        mold_new_tips_page.should_be_get_ready_page_title()

    def test_mnt_molding(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenUpdateDialogPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        menu_page = MenuPage(driver)
        mold_new_tips_page = MoldNewTipsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        landing_page.check_bt_dialog_presence_and_accept_it()
        dialog_page.check_and_close_fw_update_dialog()
        time.sleep(10)
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_mold_new_tips_item()
        # Carousel
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_match_them_up_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_check_the_fit_title()
        mold_new_tips_page.tap_next_button()
        # How to pair screen
        mold_new_tips_page.should_be_got_it_button()
        mold_new_tips_page.tap_got_it_button()
        # Try them on screen
        time.sleep(10)
        mold_new_tips_page.should_be_try_them_button()
        mold_new_tips_page.tap_try_them_button()
        # Get ready screen
        mold_new_tips_page.should_be_get_ready_page_title()
        mold_new_tips_page.tap_do_this_button()
        # How is the bass
        mold_new_tips_page.should_be_how_is_bass_title()
        time.sleep(20)
        # Starting soon 1
        mold_new_tips_page.should_be_starting_soon_title()
        mold_new_tips_page.should_be_starting_soon_subtitle1()
        time.sleep(4)
        # Starting soon 2
        mold_new_tips_page.should_be_starting_soon_title()
        mold_new_tips_page.should_be_starting_soon_subtitle2()
        # Molding starts
        time.sleep(45)
        mold_new_tips_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        mold_new_tips_page.should_be_congratulations_title()
        mold_new_tips_page.should_be_congratulations_subtitle()
        mold_new_tips_page.should_be_finish_button()
        mold_new_tips_page.tap_finish_button()
        home_page.should_be_hamburger_menu()

    def test_firmware_update(self, driver):
        analytics_page = AnalyticsPage(driver)
        email_entry_page = EmailEntryPage(driver)
        firmware_update_page = FirmwareUpdatePage(driver)
        dialog_page = HomeScreenUpdateDialogPage(driver)
        home_page = HomePage(driver)
        menu_page = MenuPage(driver)
        support_page = SupportPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        email_entry_page.should_be_email_entry_title()
        email_entry_page.should_be_correct_email_entry_subtitle()
        email_entry_page.tap_no_thanks_button()
        analytics_page.tap_share_analytics_button()
        analytics_page.check_bt_dialog_presence_and_accept_it()
        time.sleep(10)
        dialog_page.check_and_close_fw_update_dialog()
        home_page.should_be_hamburger_menu()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_support_item()
        support_page.should_be_firmware_item()
        support_page.tap_firmware_item()
        time.sleep(2)
        firmware_update_page.check_push_notification_dialog_presence()
        time.sleep(3)
        # firmware_update_page.should_up_to_date_title()
        firmware_update_page.activate_fw_update()
        time.sleep(5)
        # firmware_update_page.is_update_available_title()
        # firmware_update_page.tap_update_earbuds_button()
        firmware_update_page.should_be_ready_to_update_title()
        firmware_update_page.tap_install_now_button()
        time.sleep(15)
        firmware_update_page.check_active_update()

# run with
# pytest -s -v --reruns 1 -m smoke_test --html=/Users/rudiuk/PyCharmProjects/ios_appium_project/test_report/report.html --capture sys
